#
###################################
# Site wide configuration
####################################
#
title: Ahmed Alshamary
email: ahmedralshamary@gmail.com
description: Ahmed Alshamary's Site
url: https://ahmedalshamary.com


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Ahmed Alshamary
  avatar: leonids-logo.png
  job: "Something or Another"
  bio: "Ahmed is a prisoner at Georgetown."
  email: ahmedralshamary@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-93134018-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ahmedalshamary
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ahmed-alshamary-3b25b6a1
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
